services:
  timescaledb:
    image: timescale/timescaledb:2.24.0-pg18
    shm_size: '2gb'
    container_name: test_stock_model_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - test_stock_data:/var/lib/postgresql
      - ./data:/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      timeout: 5s

  pipeline:
    build:
      context: ./src/pipeline
      dockerfile: Dockerfile
    image: stock_model-ohlcv_pipeline:latest
    container_name: ohlcv_pipeline
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      DB_HOST: timescaledb
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    volumes:
      - ./data:/data

volumes:
  test_stock_data:
