"""add clean_ohlcv table

Revision ID: d946abd4d617
Revises: 73b0e97a4859
Create Date: 2026-02-26 18:29:47.518933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd946abd4d617'
down_revision: Union[str, Sequence[str], None] = '73b0e97a4859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clean_ohlcv',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('high', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('low', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('close', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('dividends', sa.Float(), nullable=True),
    sa.Column('stock_splits', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ticker'], ['companies.ticker'], ),
    sa.PrimaryKeyConstraint('ticker', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clean_ohlcv')
    # ### end Alembic commands ###
